"""initial

Revision ID: 71c5feaf11ee
Revises:
Create Date: 2021-08-24 22:06:40.516212

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "71c5feaf11ee"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installed_modules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("module_name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("installation_date", sa.DateTime(), nullable=True),
        sa.Column("functions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("installed_modules")
    # ### end Alembic commands ###
