"""Version 1.0.0 migration

Revision ID: 7821cb7e254d
Revises: 
Create Date: 2021-06-14 13:16:52.338594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7821cb7e254d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bases',
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('local_name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('database', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('con_args', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('local_name')
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('granted_tables', postgresql.ARRAY(sa.TEXT(), dimensions=1), nullable=True),
    sa.Column('admin_access', sa.Boolean(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('main_admin', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('tables_info',
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('folder_name', sa.String(), nullable=True),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('local_name', sa.String(), nullable=False),
    sa.Column('columns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['database_name'], ['bases.local_name'], ),
    sa.PrimaryKeyConstraint('database_name', 'local_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables_info')
    op.drop_table('tokens')
    op.drop_table('bases')
    # ### end Alembic commands ###
