ADMIN_TOKEN_FIELD_NAME = "admin_token"
USER_TOKEN_FIELD_NAME = "user_token"

POST_REQUEST_TYPE_FIELD_NAME = "request_type"

USER_TOKEN_NAME_FIELD_NAME = "token_name"

DESCRIPTION_FIELD_NAME = "description"

LOCAL_TABLE_NAME_FILED_NAME = "local_table_name"
NEW_LOCAL_TABLE_NAME_FILED_NAME = "new_local_table_name"

DATABASE_NAME_FIELD_NAME = "database"
FOLDER_NAME_FIELD_NAME = "folder"
TABLE_NAME_FIELD_NAME = "table"

DATABASE_IP_FIELD_NAME = "ip"
DATABASE_PORT_FIELD_NAME = "port"
DATABASE_DB_NAME_FIELD_NAME = "database"
DATABASE_USER_FIELD_NAME = "username"
DATABASE_PASSWORD_FIELD_NAME = "password"
LOCAL_DATABASE_NAME_FIELD_NAME = "local_database_name"
DATABASE_TYPE_FIELD_NAME = "base_type"
