ADMIN_TOKEN_FIELD_NAME = "admin_token"
USER_TOKEN_FIELD_NAME = "user_token"

DESCRIPTION_FIELD_NAME = "description"
LOCAL_TABLE_NAME_FILED_NAME = "local_table_name"

DATABASE_NAME_FIELD_NAME = "database"
FOLDER_NAME_FIELD_NAME = "folder"
TABLE_NAME_FIELD_NAME = "table"
