name: Module tests with pytest
on: push


jobs:

   pytest-job:
     runs-on: ubuntu-latest

     steps:
       - name: "Export version"
         run: export RELEASE_VERSION=$(cat VERSION)

       - name: Publish Docker to Docker Hub
         uses: elgohr/Publish-Docker-Github-Action@master
         with:
           name: catalystteam/catalyst
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           dockerfile: Dockerfile
           tags: "${{ env.RELEASE_VERSION }}"
