name: Module tests with pytest
on: push


jobs:

   tests-with-pytest:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2
       - name: "Install Requirements"
         run: |
          pip3 install -r requirements.txt
       - name: "Run tests"
         run: |
          pytest -v
