name: Push image to DockerHub
on:
  push:
    branches:
      - develop
      - RB-*
      - fastapi

jobs:

   Dockerhub:
     runs-on: ubuntu-latest

     services:
       postgres:
         image: postgres
         env:
           POSTGRES_PASSWORD: password
           POSTGRES_HOST_AUTH_METHOD: trust
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5

     steps:
       - uses: actions/checkout@v2

       - name: "Build image"
         run: docker build -t test_restbase .

       - name: "Start container"
         run: docker run --name test_restbase -p 54541:54541 -d test_restbase

#       - name: "Curl test"
#         run: "curl localhost:54541/AdminToken/GenerateFirstToken/"

       - name: "Export version"
         run: export RELEASE_VERSION=$(cat VERSION)

       - name: Publish Docker to Docker Hub
         uses: elgohr/Publish-Docker-Github-Action@master
         with:
           name: restbase/restbase-server-dev
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           dockerfile: Dockerfile
           tags: "${{ env.RELEASE_VERSION }}"
