name: Push image to DockerHub
on:
  push:
    branches:
      - develop
      - RB-*
      - fastapi

jobs:

   Dockerhub Job:
     runs-on: ubuntu-latest

     steps:
       - name: "Export version"
         run: export RELEASE_VERSION=$(cat VERSION)

       - name: Publish Docker to Docker Hub
         uses: elgohr/Publish-Docker-Github-Action@master
         with:
           name: restbase/restbase-server-dev
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           dockerfile: Dockerfile
           tags: "${{ env.RELEASE_VERSION }}"
