name: Push image to DockerHub
on:
  push:
    branches:
      - RB-*

jobs:

   Tests:
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       max-parallel: 4
       matrix:
         postgres_image: ["postgres:12", "postgres:11", "postgres:10", "postgres:latest"]
     steps:
       - uses: actions/checkout@v2

       - name: "Build image"
         run: docker build -t restbase/restbase-server-dev:$(cat VERSION) .

       - name: "Prepare infrastructure"
         run: |
           cd test/
           docker network create restbase_test_network
           docker-compose up -d

       - name: "Start container"
         run: docker run --network="restbase_test_network" --name test_restbase -p 54541:54541 -e TEST='test' -d restbase/restbase-server-dev:$(cat VERSION)

       - name: "Install requirements for tests"
         run: pip3 install -r test/requirements.txt

       - name: "Check logs"
         run: docker logs test_restbase

       - name: "Tests"
         run: pytest -v test/


   Dockerhub:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: "Build image"
         run: docker build -t restbase/restbase-server-dev:${GITHUB_REF##*/} .

       - name: Publish on Docker hub
         run: |
           echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
           docker push restbase/restbase-server-dev:${GITHUB_REF##*/}
