name: reviewdog
on: [pull_request]
jobs:
  flake8:
    name: runner / pyflakes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: flake8
        uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ secrets.CODESTYLE_TOKEN }}
          reporter: github-pr-check
